{
  "openapi": "3.0.0",
  "info": {
    "version": "v1.0.0",
    "title": "Swagger Demo Project",
    "description": "Implementation of Swagger with TypeScript"
  },
  "servers": [
    {
      "url": "http://localhost:8000/api/",
      "description": ""
    }
  ],
  "paths": {
    "/": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "Login response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/loginSchema"
                },
                "example": {
                  "status": true,
                  "data": {
                    "email": "johndoe@sample.com",
                    "fullname": "John Doe",
                    "phone": "08012345678"
                  },
                  "message": "Successful message"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/loginSchema"
              },
              "example": {
                "email": "johndoe@sample.com",
                "password": "password"
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "Register response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/registerSchema"
                },
                "example": {
                  "status": true,
                  "data": {
                    "email": "johndoe@sample.com",
                    "fullname": "John Doe",
                    "phone": "08012345678"
                  },
                  "message": "Successful message"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/registerSchema"
              },
              "example": {
                "email": "johndoe@sample.com",
                "password": "password",
                "fullname": "John Doe",
                "phone": "08012345678"
              }
            }
          }
        }
      }
    },
    "/auth/forgot-password": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "Forgot response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/forgotPasswordSchema"
                },
                "example": {
                  "status": true,
                  "message": "Successfull message"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/forgotPasswordSchema"
              },
              "example": {
                "email": "johndoe@sample.com",
                "password": "password"
              }
            }
          }
        }
      }
    },
    "/auth/verify-token": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "Forgot response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/verifyTokenSchema"
                },
                "example": {
                  "status": true,
                  "message": "Successfull message"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/verifyTokenSchema"
              },
              "example": {
                "otp": "johndoe@sample.com"
              }
            }
          }
        }
      }
    },
    "/auth/reset-password": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "Forgot response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/verifyTokenSchema"
                },
                "example": {
                  "status": true,
                  "message": "Successfull message"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/verifyTokenSchema"
              },
              "example": {
                "otp": "johndoe@sample.com"
              }
            }
          }
        }
      }
    },
    "/dashboard": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/truck/": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "patch": {
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "loginSchema": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "johno@sample.com"
          },
          "password": {
            "type": "string",
            "example": "password"
          }
        },
        "required": [
          "email",
          "password"
        ]
      },
      "registerSchema": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "johno@sample.com"
          },
          "password": {
            "type": "string",
            "example": "password"
          },
          "fullname": {
            "type": "string",
            "example": "John doe"
          },
          "phone": {
            "type": "string",
            "example": "08012345678"
          }
        },
        "required": [
          "email",
          "password",
          "fullname",
          "phone"
        ]
      },
      "forgotPasswordSchema": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "johno@sample.com"
          }
        },
        "required": [
          "email"
        ]
      },
      "verifyTokenSchema": {
        "type": "object",
        "properties": {
          "otp": {
            "type": "string",
            "example": "123456"
          }
        },
        "required": [
          "otp"
        ]
      },
      "resetPasswordSchema": {
        "type": "object",
        "properties": {
          "otp": {
            "type": "string",
            "example": "johno@sample.com"
          },
          "password": {
            "type": "string",
            "example": "Password"
          }
        },
        "required": [
          "otp",
          "password"
        ]
      }
    }
  }
}